version: '3'

services:
  coursematerial:
    image: juhojo/dockerhy-circleci
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
